#!/usr/bin/env atf-sh
# -*- shell-script -*-

atf_test_case simple_issue
simple_issue_head()
{
	atf_set "descr" "parse a simple issue"
}
simple_issue_body()
{
	SAMPLE_DATA=$(atf_get_srcdir)/samples/github_simple_issue.json
	OUTPUTFILE=$(mktemp)

	$GH_TEST issue < $SAMPLE_DATA > $OUTPUTFILE || atf_fail "Could not parse data"


	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^title' | cut -f2-)" \
		"consider removing FILE *out from printing functions"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^number' | cut -f2-)" \
		"115"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^author' | cut -f2-)" \
		"herrhotzenplotz"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^state' | cut -f2-)" \
		"closed"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^locked' | cut -f2-)" \
		"0"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^labels_size' | cut -f2-)" \
		"0"

	atf_check_equal \
		"$(cat $OUTPUTFILE | grep '^comments' | cut -f2-)" \
		"0"
}

atf_init_test_cases()
{
	GH_TEST=$(atf_get_srcdir)/github-tests
	[ -x ${GH_TEST} ] || atf_fail "Missing Github test executable"

	atf_add_test_case simple_issue
}
