PORTNAME=	gcli
DISTVERSION=	0.9.8
DISTVERSIONSUFFIX=	-beta
MAINTAINER=	nsonack@outlook.com
CATEGORIES=	devel

LICENSE=	BSD2CLAUSE

USES=		pkgconfig:build
USE_GITLAB=	yes
GL_COMMIT=	3aadaf7d0787bd3cfa5682d330d76c26fc332773
GL_ACCOUNT=	herrhotzenplotz

LIB_DEPENDS=	libcurl.so:ftp/curl

.include <bsd.port.mk>
