PORTNAME=	gcli
DISTVERSION=	0.9.9
DISTVERSIONSUFFIX=	-beta
MAINTAINER=	nsonack@outlook.com
CATEGORIES=	devel

LICENSE=	BSD2CLAUSE

USES=		pkgconfig:build
USE_GITLAB=	yes
GL_COMMIT=	d390d9a7074029be5842959939e63beaf12c4f31
GL_ACCOUNT=	herrhotzenplotz

LIB_DEPENDS=	libcurl.so:ftp/curl

.include <bsd.port.mk>
