.Dd $Mdocdate$
.Dt GHCLI-STATUS 1
.Os
.Sh NAME
.Nm ghcli status
.Nd Print a list of notifications and/or TODOs
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
prints a list of TODOs and notifications on the given account.
.Sh OPTIONS
None.
.Sh EXAMPLES
Print a TODO list for my-account:
.Bd -literal -offset indent
$ ghcli -a my-account status
.Ed

.Sh SEE ALSO
.Xr ghcli 1 ,
.Xr ghcli-issues 1 ,
.Xr ghcli-pulls 1
.Sh AUTHORS
.An Nico Sonack aka. herrhotzenplotz Aq Mt nsonack@herrhotzenplotz.de
.Sh BUGS
Please report issues preferably via e-mail or on GitHub.
