.Dd $Mdocdate$
.Dt GHCLI 1
.Os
.Sh NAME
.Nm ghcli
.Nd is a command-line utility to interact with GitHub without using a web-browser.
.Sh SYNOPSIS

.Nm
.Cm issues
.Op Fl o Ar user-or-organization Fl r Ar repository Op Fl a
.Op Fl i Ar issue Ar ...

.Nm
.Cm pulls
.Op Fl o Ar user-or-organization Fl r Ar repository Op Fl a
.Op Fl p Ar #PR Ar ...

.Nm
.Cm pulls create
.Op Fl -from Ar org:branch
.Op Fl -to Ar trunk
.Op Fl -in Ar upstream/repo
.Ar PR-Title

.Nm
.Cm comment
.Op Fl i Ar issue
.Op Fl p Ar pr

.Sh DESCRIPTION
The
.Nm
retrieves or submits data to the GitHub API to list issues and
pull requests on specific
.Xr git 1
repositories hosted on GitHub.

.Sh SUBCOMMANDS
.Bl -tag -width indent

.It Cm issues
lists open issues on the given or auto-detected repository.
If
.Fl a
was specified, all issues including closed ones, are listed.
.Fl i
can be used to fetch detailed information about a single issue.
You can specify one or more operations:

.Bl -tag -width indent
.It Cm summary
Print a summary.
.It Cm comments
Print the comment section of the issue.
.El

.It Cm pulls
lists open pull requests on the given repository.

The repository can be either specified through the
.Fl o
and
.Fl r
flags or, if unspecified,
.Nm
will try to autodetect the correct remote using the git config.

If a PR number is specified, you can append one or more of the
following operations to perform on the given pull request:

.Bl -tag -width indent
.It Cm summary
Print a summary.
.It Cm comments
Print the comment section of the PR.
.It Cm diff
Print the PR diff.
.It Cm merge
Performs a merge of the PR and closes it.
.It Cm close
Sets the state of the PR to closed.
.It Cm reopen
Sets the state of the PR to open.
.El

.It Cm pulls create
foobar

.It Cm comment
create a new comment under the issue specified by
.Fl i
or the PR specified by
.Fl p .
This will open an editor and ask for confirmation.

.El

.Sh OPTIONS
.Bl -tag -width indent

.It Fl a
Fetch all data, including closed issues and closed/merged PRs.

.It Fl o Ar org
Operate on the given organization/user.
Can only be used in combination with
.Fl r .

.It Fl r Ar repo
Operate on the given repository.
Can only be used in combination with
.Fl o .

.It Fl i Ar id
Operate on the given issue number.

.It Fl p Ar pr
Operate on the given pull request.

.It Fl -from , Fl f Ar org:branch
Create a pull request from the specified target as the head. You may
omit this flag if you are currently on branch to be PRed and have the
account field in your config file set. See
.Sx FILES
for more details.

.It Fl -to , Fl t Ar branch
Specifies the branch into which the merge of the PR is being
requested. You may omit this flag if you have the base field set
in the
.Pa .ghcli
file. See
.Sx FILES
for more details.

.It Fl -in , Fl i Ar org/repo
If a PR is created, it will be submitted to the given repository. You
may omit this flag if you have the upstream field in the
.Pa .ghcli
file set. See
.Sx FILES
for more details.
The
.Fl i
flag is only valid in the
.Cm pulls create
subcommand. It has a different meaning in all other contexts.


.El

.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.Sh FILES
.Bl -tag -width ${XDG_CONFIG_DIR}/ghcli/config -compact

.It Pa ${XDG_CONFIG_DIR}/ghcli/config
The config file for
.Nm .
It shall contain the following data:

.Bd -literal
api_token=<valid github api token>
editor=/path/to/ganoooo/emacs
account=herrhotzenplotz
.Ed

If editor is not set in the config file,
.Nm
will use
.Ev EDITOR
from the environment.

.It Pa .ghcli
A repo-specific config file that may contain the following data:
.Bd -literal
upstream=herrhotzenplotz/ghcli
base=trunk
.Ed

It is intended to be committed into the repo so that users don't have
to manually specify all the options like
.Fl -in ,
.Fl -from ,
.Fl -base etc.

.El


.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Sh EXAMPLES
Look at PR #78 in vim/colorschemes:

ghcli pulls -o vim -r colorschemes -p 78 summary comments | less

.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.

.Sh SEE ALSO
.Xr git 1

.\" .Sh STANDARDS
.Sh HISTORY
The idea for
.Nm
appeared during a long rant on IRC where the issue with the official
tool written by GitHub became clear to be the manual dialing and DNS
resolving by the Go runtime, circumventing almost the entirety of the
OS TCP/IP stack and leaking sensitive information when using Tor.

Implementation started in October 2021 with the goal of having a
decent, sufficiently portable and secure version of a cli utility to
interact with the GitHub world without using the horrible web
interface.

.Sh AUTHORS
.An Nico Sonack aka. herrhotzenplotz Aq Mt nsonack@outlook.com
.\" .Sh CAVEATS

.Sh BUGS
Yes. It is software.

Please report issues preferably via e-mail or on GitHub.

.Sh SECURITY CONSIDERATIONS
It is written in C. If it were written in Rust, it would have been
much safer.
